name: faraid_a_z
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  hijri: ^3.0.0
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/Faraid_A-Z.png
    - lib/assets/images/faraid_logo.png
    - lib/assets/images/Gemini_Generated_Image_1.png
    - lib/assets/images/buku_madad.jpeg
